upstream ytcraft_indonesia {
    server 127.0.0.1:3000;
    keepalive 64;
}

server {
    listen 80;
    server_name ytcraft.id cv.ytcraft.id www.ytcraft.id;

    client_max_body_size 50M;

    location / {
        proxy_pass http://ytcraft_indonesia;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    location /_next/static {
        alias /Users/ytcraft/Sites/ytcraft-indonesia/.next/static;
        expires 365d;
        access_log off;
    }

    location /public {
        alias /Users/ytcraft/Sites/ytcraft-indonesia/public;
        expires 30d;
        access_log off;
    }
}
